#워크 플로의 이르 지정
name: Main_workflows

# 워크 플로우의 특징 정의
on:
  workflow_dispatch:
    inputs:
      environment:
        description: '배포 환경'
        required: true
        default: 'staging'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "test"